// src/constants/nodeTypes.ts
// Single source of truth for visual representation of each Pywr node type.
// Colours, shapes, display labels, and default fields when creating new nodes.
// All node types derive from PYWR_SCHEMA.md.
// No Math.random(). No invented colours (#000000, #ffffff not used).

import { PywrNode } from "../types/pywr";

// ---------------------------------------------------------------------------
// Shape types
// ---------------------------------------------------------------------------
export type NodeShapeType = "diamond" | "rectangle" | "circle" | "hexagon";
export type NodeBorderStyle = "solid" | "dashed" | "thick";

export interface NodeShape {
  shape: NodeShapeType;
  border: NodeBorderStyle;
}

// ---------------------------------------------------------------------------
// NODE_COLOUR_MAP — one entry per Pywr node type from PYWR_SCHEMA.md
// ---------------------------------------------------------------------------
export const NODE_COLOUR_MAP: Record<string, string> = {
  Input:                "#3B8BD4",  // blue
  Catchment:            "#3B8BD4",  // blue
  Link:                 "#EF9F27",  // amber
  Output:               "#1D9E75",  // teal
  Storage:              "#7F77DD",  // purple
  VirtualStorage:       "#888780",  // grey
  AnnualVirtualStorage: "#888780",  // grey
  PiecewiseLink:        "#EF9F27",  // amber
  AggregatedNode:       "#D85A30",  // coral
  AggregatedStorage:    "#D85A30",  // coral
  River:                "#5DCAA5",  // light teal
  RiverGauge:           "#5DCAA5",  // light teal
  RiverSplitWithGauge:  "#5DCAA5",  // light teal
};

// ---------------------------------------------------------------------------
// NODE_SHAPE_MAP — one entry per Pywr node type
// ---------------------------------------------------------------------------
export const NODE_SHAPE_MAP: Record<string, NodeShape> = {
  Input:                { shape: "diamond",   border: "solid" },
  Catchment:            { shape: "diamond",   border: "solid" },
  Link:                 { shape: "rectangle", border: "solid" },
  Output:               { shape: "rectangle", border: "solid" },
  Storage:              { shape: "circle",    border: "solid" },
  VirtualStorage:       { shape: "circle",    border: "dashed" },
  AnnualVirtualStorage: { shape: "rectangle", border: "dashed" },
  PiecewiseLink:        { shape: "rectangle", border: "thick" },
  AggregatedNode:       { shape: "hexagon",   border: "solid" },
  AggregatedStorage:    { shape: "circle",    border: "solid" },
  River:                { shape: "rectangle", border: "dashed" },
  RiverGauge:           { shape: "rectangle", border: "dashed" },
  RiverSplitWithGauge:  { shape: "diamond",   border: "solid" },
};

// ---------------------------------------------------------------------------
// NODE_DISPLAY_LABELS — human-friendly name for each node type
// ---------------------------------------------------------------------------
export const NODE_DISPLAY_LABELS: Record<string, string> = {
  Input:                "Input",
  Catchment:            "Catchment",
  Link:                 "Link",
  Output:               "Output (Demand)",
  Storage:              "Reservoir / Storage",
  VirtualStorage:       "Virtual Storage",
  AnnualVirtualStorage: "Annual Licence (VS)",
  PiecewiseLink:        "Piecewise Link",
  AggregatedNode:       "Aggregated Node",
  AggregatedStorage:    "Aggregated Storage",
  River:                "River",
  RiverGauge:           "River Gauge",
  RiverSplitWithGauge:  "River Split w/ Gauge",
};

// ---------------------------------------------------------------------------
// NODE_DEFAULT_FIELDS — minimum valid fields when creating a new node.
// name is NOT included here — it is generated by NodePalette with uniqueness.
// All required fields from PYWR_SCHEMA.md are included.
// ---------------------------------------------------------------------------
export const NODE_DEFAULT_FIELDS: Record<string, Partial<PywrNode>> = {
  Input:                { type: "Input" } as Partial<PywrNode>,
  Catchment:            { type: "Catchment" } as Partial<PywrNode>,
  Link:                 { type: "Link" } as Partial<PywrNode>,
  Output:               { type: "Output" } as Partial<PywrNode>,
  Storage:              { type: "Storage", max_volume: 0, initial_volume_pc: 1.0 } as Partial<PywrNode>,
  VirtualStorage:       { type: "VirtualStorage", nodes: [] } as Partial<PywrNode>,
  AnnualVirtualStorage: { type: "AnnualVirtualStorage", nodes: [], max_volume: 0 } as Partial<PywrNode>,
  PiecewiseLink:        { type: "PiecewiseLink", nsteps: 2 } as Partial<PywrNode>,
  AggregatedNode:       { type: "AggregatedNode", nodes: [] } as Partial<PywrNode>,
  AggregatedStorage:    { type: "AggregatedStorage", storages: [] } as Partial<PywrNode>,
  River:                { type: "River" } as Partial<PywrNode>,
  RiverGauge:           { type: "RiverGauge" } as Partial<PywrNode>,
  RiverSplitWithGauge:  { type: "RiverSplitWithGauge" } as Partial<PywrNode>,
};

// Ordered list of all node types — used for palette iteration
export const NODE_TYPES: string[] = Object.keys(NODE_COLOUR_MAP);
